(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { modules: [], selected: null, modulePermissions: {}, catalog: { guilds: [], publications: [], roles: [] } };
  const endpoint = 'manage-platform-pages';
  const limitsField = document.createElement('div'); limitsField.className='field'; limitsField.innerHTML='<label>Reguli și limite</label><div class="grid gap-2 sm:grid-cols-2"><input id="module-cooldown" class="field-input" type="number" min="0" max="86400" placeholder="Cooldown în secunde (0 = fără limită)"><input id="module-max-requests" class="field-input" type="number" min="0" max="10000" placeholder="Cereri / 24h (0 = fără limită)"></div><small class="muted">Atașamentele se trimit printr-un câmp URL, deoarece modalurile Discord nu acceptă fișiere.</small>'; document.getElementById('module-form')?.parentElement?.after(limitsField);
  const permissionsField = document.createElement('div'); permissionsField.className='field'; permissionsField.innerHTML='<span>Rolurile se aleg la publicarea modulului</span><small class="muted">După alegerea organizației și serverului, selectezi rolurile care pot folosi sau aproba modulul. Nu trebuie copiate ID-uri.</small>'; limitsField.after(permissionsField);
  const slashField = document.createElement('div'); slashField.className='field'; slashField.innerHTML='<label class="flex items-center gap-2"><input id="module-slash-enabled" type="checkbox"> Activează comanda slash pentru acest modul</label><small class="muted">După publicare, apasă „Sincronizează slash” pentru serverul ales.</small>'; permissionsField.after(slashField);
  const responsesField = document.createElement('div'); responsesField.className='field'; responsesField.innerHTML='<label>Răspunsuri configurabile</label><div class="grid gap-2 sm:grid-cols-2"><input id="module-response-button" class="field-input" placeholder="Răspuns la acțiune"><input id="module-response-success" class="field-input" placeholder="Mesaj de succes"><input id="module-response-error" class="field-input" placeholder="Mesaj de eroare"><input id="module-response-review" class="field-input" placeholder="Mesaj pentru aprobare"></div>'; slashField.after(responsesField);
  const buttonsBuilder = document.createElement('div'); buttonsBuilder.className='field'; buttonsBuilder.innerHTML='<div class="flex items-center justify-between gap-2"><label>Buton(e) și acțiuni</label><button type="button" class="button" id="add-module-button">＋ Adaugă buton</button></div><div id="module-buttons-builder" class="module-list"></div>'; $('module-buttons')?.parentElement?.after(buttonsBuilder); $('module-buttons').parentElement.hidden=true;
  const fieldsBuilder = document.createElement('div'); fieldsBuilder.className='field'; fieldsBuilder.innerHTML='<div class="flex items-center justify-between gap-2"><label>Câmpuri formular</label><button type="button" class="button" id="add-module-field">＋ Adaugă câmp</button></div><div id="module-fields-builder" class="module-list"></div>'; $('module-form')?.parentElement?.after(fieldsBuilder); $('module-form').parentElement.hidden=true;
  const status = (text, kind = '') => { const node = $('module-status'); if (node) { node.textContent = text; node.className = `status ${kind}`; } };
  const call = async (body) => window.panelRequestJson(endpoint, { method: 'POST', body: JSON.stringify(body), timeoutMs: 12000 });
  const publicationCall = async (body) => window.panelRequestJson('manage-panel-modules', { method: 'POST', body: JSON.stringify(body), timeoutMs: 30000 });
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const sample = (type) => ({ announcement:{label:'Anunț / comunicare',description:'Publică un mesaj clar pentru comunitate.',handler:'announcement',buttons:[{label:'Publică anunțul',action:'open_form'}],form_schema:[{id:'message',label:'Mesaj',type:'long_text',required:true}]}, request:{label:'Cerere / formular',description:'Colectează cereri de la membri.',handler:'request',buttons:[{label:'Trimite cererea',action:'open_form'}],form_schema:[{id:'subject',label:'Subiect',type:'short_text',required:true},{id:'details',label:'Detalii',type:'long_text',required:true}]}, approval:{label:'Cerere cu aprobare',description:'Trimite cereri staffului pentru aprobare sau respingere.',handler:'approval',buttons:[{label:'Trimite spre aprobare',action:'open_form'}],form_schema:[{id:'subject',label:'Subiect',type:'short_text',required:true},{id:'details',label:'Detalii',type:'long_text',required:true}]}, report:{label:'Raport / statistici',description:'Generează un raport din înregistrările modulului.',handler:'report',buttons:[{label:'Generează raport',action:'report'}],form_schema:[]}, none:{label:'Modul personalizat',description:'Pornește de la zero.',handler:'none',buttons:[],form_schema:[]}}[type] || {});
  function parse(value, fallback) { try { const parsed = JSON.parse(value || ''); return parsed; } catch (_) { return fallback; } }
  const actionOptions = [['open_form','Deschide formular'],['save_submission','Salvează cererea'],['send_log','Trimite rezultat'],['report','Generează raport'],['approve','Aprobă cerere'],['reject','Respinge cerere'],['update_message','Actualizează embedul'],['notify_submitter','Notifică utilizatorul']];
  function addButton(data={}) { const row=document.createElement('div'); row.className='module-choice'; row.dataset.builderButton='1'; row.innerHTML=`<div class="grid gap-2 sm:grid-cols-[1fr_190px_34px]"><input data-button-label class="field-input" placeholder="Text buton"><select data-button-action class="field-input">${actionOptions.map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><button type="button" data-remove-builder class="button">×</button></div>`; row.querySelector('[data-button-label]').value=data.label||''; row.querySelector('[data-button-action]').value=data.action||'open_form'; row.querySelector('[data-remove-builder]').onclick=()=>row.remove(); $('module-buttons-builder').appendChild(row); }
  function addField(data={}) { const row=document.createElement('div'); row.className='module-choice'; row.dataset.builderField='1'; row.innerHTML=`<div class="grid gap-2 sm:grid-cols-2"><input data-field-id class="field-input" placeholder="Identificator (ex: subiect)"><input data-field-label class="field-input" placeholder="Etichetă afișată"><select data-field-type class="field-input"><option value="short_text">Text scurt</option><option value="long_text">Text lung</option><option value="url">Link URL</option></select><input data-field-placeholder class="field-input" placeholder="Placeholder"><label class="flex items-center gap-2 text-xs"><input data-field-required type="checkbox"> Obligatoriu</label><button type="button" data-remove-builder class="button">Șterge câmpul</button></div>`; row.querySelector('[data-field-id]').value=data.id||''; row.querySelector('[data-field-label]').value=data.label||''; row.querySelector('[data-field-type]').value=data.type||'short_text'; row.querySelector('[data-field-placeholder]').value=data.placeholder||''; row.querySelector('[data-field-required]').checked=data.required!==false; row.querySelector('[data-remove-builder]').onclick=()=>row.remove(); $('module-fields-builder').appendChild(row); }
  const readButtons=()=>[...document.querySelectorAll('[data-builder-button]')].map((row)=>({label:row.querySelector('[data-button-label]').value.trim(),action:row.querySelector('[data-button-action]').value})).filter((item)=>item.label);
  const readFields=()=>[...document.querySelectorAll('[data-builder-field]')].map((row)=>({id:row.querySelector('[data-field-id]').value.trim(),label:row.querySelector('[data-field-label]').value.trim(),type:row.querySelector('[data-field-type]').value,placeholder:row.querySelector('[data-field-placeholder]').value.trim(),required:row.querySelector('[data-field-required]').checked})).filter((item)=>item.id||item.label);
  const renderBuilders=(buttons=[],fields=[])=>{ $('module-buttons-builder').replaceChildren(); $('module-fields-builder').replaceChildren(); buttons.forEach(addButton); fields.forEach(addField); };
  function read() { return { module_key:$('module-key').value.trim().toLowerCase(), label:$('module-label').value.trim(), description:$('module-description').value.trim(), definition:{handler:$('module-handler').value, buttons:readButtons(), form_schema:readFields(), limits:{cooldown_seconds:Number($('module-cooldown')?.value || 0),max_requests:Number($('module-max-requests')?.value || 0)}, permissions:state.modulePermissions || {}, slash_command:{enabled:Boolean($('module-slash-enabled')?.checked)}, responses:{button:$('module-response-button')?.value.trim() || '',success:$('module-response-success')?.value.trim() || '',error:$('module-response-error')?.value.trim() || '',review:$('module-response-review')?.value.trim() || ''}} }; }
  function fill(item) { const d=item?.definition || {}; const responses=d.responses || {}; state.modulePermissions=d.permissions && typeof d.permissions === 'object' ? d.permissions : {}; $('module-editor-title').textContent = item?.label ? `Editează ${item.label}` : 'Modul nou'; $('module-key').value=item?.module_key || ''; $('module-label').value=item?.label || ''; $('module-description').value=item?.description || ''; $('module-handler').value=d.handler || 'none'; renderBuilders(d.buttons || [],d.form_schema || []); $('module-cooldown').value=Number(d.limits?.cooldown_seconds || 0) || ''; $('module-max-requests').value=Number(d.limits?.max_requests || 0) || ''; $('module-slash-enabled').checked=d.slash_command?.enabled === true; $('module-response-button').value=responses.button || ''; $('module-response-success').value=responses.success || ''; $('module-response-error').value=responses.error || ''; $('module-response-review').value=responses.review || ''; state.selected=item?.module_key || null; renderList(); }
  function renderList() { $('module-list').innerHTML = state.modules.length ? state.modules.map((m) => `<button type="button" class="module-choice ${m.module_key===state.selected?'active':''}" data-module="${esc(m.module_key)}"><strong>${esc(m.label)}</strong><br><small class="muted">${esc(m.description || 'Fără descriere')}</small></button>`).join('') : '<p class="muted text-xs">Nu există șabloane. Creează primul modul.</p>'; document.querySelectorAll('[data-module]').forEach((button) => button.addEventListener('click', () => fill(state.modules.find((m) => m.module_key === button.dataset.module)))); }
  function preview() { const item=read(); const box=$('module-preview-box'); box.hidden=false; box.innerHTML=`<h3>${esc(item.label || 'Modul fără nume')}</h3><p>${esc(item.description || 'Fără descriere')}</p><div>${(item.definition.buttons || []).map((b) => `<span class="tag">${esc(b.label || 'Buton')} · ${esc(b.action || 'none')}</span>`).join('') || '<span class="muted text-xs">Fără butoane</span>'}</div><p class="muted">Handler: ${esc(item.definition.handler || 'none')} · Câmpuri: ${item.definition.form_schema?.length || 0}</p>`; }
  const publicationStatus = (text, kind = '') => { const node = $('publication-status'); if (node) { node.textContent = text; node.className = `status ${kind}`; } };
  const publicationFields = () => ({ module_key: $('publication-module').value, organization_id: $('publication-organization').value || undefined, guild_id: $('publication-guild').value, target: $('publication-target').value, embed_channel_id: $('publication-embed-channel').value.trim(), result_channel_id: $('publication-result-channel').value.trim(), message_id: $('publication-embed-channel').dataset.messageId || '', permissions: { allowed_role_ids: [...document.querySelectorAll('[data-publication-role="allowed"]:checked')].map((box) => box.value), approval_role_ids: [...document.querySelectorAll('[data-publication-role="approval"]:checked')].map((box) => box.value) } });
  const currentPublication = () => { const moduleKey = $('publication-module')?.value || ''; const target = $('publication-target')?.value || 'primary'; const guildId = $('publication-guild')?.value || ''; return (state.catalog.publications || []).find((item) => item.module_key === moduleKey && item.target === target && (!guildId || String(item.guild_id) === String(guildId))); };
  function ensurePublicationPermissionsHost() { const channelField = $('publication-result-channel')?.closest('.field'); if (!channelField || $('publication-permissions')) return; const node = document.createElement('div'); node.id = 'publication-permissions'; node.className = 'field'; channelField.parentElement.insertBefore(node, channelField.nextElementSibling); }
  function renderPublicationPermissions() { ensurePublicationPermissionsHost(); const host = $('publication-permissions'); if (!host) return; const guildId = $('publication-guild').value; const roleRows = (state.catalog.roles || []).filter((role) => String(role.guild_id) === String(guildId)); const current = currentPublication(); const permissions = current?.permissions || {}; const selectedAllowed = new Set((permissions.allowed_role_ids || []).map(String)); const selectedApproval = new Set((permissions.approval_role_ids || []).map(String)); if (!guildId) { host.innerHTML = '<span class="muted">Alege serverul pentru a încărca rolurile Discord.</span>'; return; } if (!roleRows.length) { host.innerHTML = '<span class="muted">Nu au fost găsite roluri configurabile pentru acest server.</span>'; return; } const group = (kind, title, selected) => `<div class="field" style="margin-top:8px"><span>${title}</span><div class="flex flex-wrap gap-2">${roleRows.map((role) => `<label class="tag" style="cursor:pointer"><input type="checkbox" value="${esc(role.id)}" data-publication-role="${kind}" ${selected.has(String(role.id)) ? 'checked' : ''}> ${esc(role.name)}</label>`).join('')}</div></div>`; host.innerHTML = '<span>Roluri Discord pentru această publicație</span>' + group('allowed', 'Poate folosi modulul', selectedAllowed) + group('approval', 'Poate aproba / respinge', selectedApproval); }
  function renderPublicationSelectors() {
    const organizationId = $('publication-organization').value || state.catalog.organization_id || '';
    const guilds = (state.catalog.guilds || []).filter((g) => !organizationId || String(g.organization_id || '') === String(organizationId));
    $('publication-guild').innerHTML = '<option value="">Selectează serverul</option>' + guilds.map((g) => `<option value="${esc(g.guild_id)}" data-kind="${esc(g.kind || 'primary')}">${esc(g.guild_name || g.guild_id)} · ${esc(g.kind || 'primary')}</option>`).join('');
    $('publication-module').innerHTML = '<option value="">Selectează modulul</option>' + state.modules.map((m) => `<option value="${esc(m.module_key)}">${esc(m.label)} · ${esc(m.module_key)}</option>`).join('');
    $('publication-list').innerHTML = (state.catalog.publications || []).filter((p) => !organizationId || String(p.organization_id || '') === String(organizationId)).map((p) => `<div class="preview"><strong>${esc(p.module_key)}</strong> · ${esc(p.target)} · <span class="tag">${esc(p.status)}</span><p class="muted">Embed: ${esc(p.embed_channel_id)} · Rezultate: ${esc(p.result_channel_id || 'neconfigurat')} · ${esc(p.message_id || 'nepublicat')} · Roluri: ${Number(p.permissions?.allowed_role_ids?.length || 0)}</p></div>`).join('') || '<p class="muted text-xs">Nu există publicații pentru organizația selectată.</p>';
    renderPublicationPermissions();
  }
  async function loadPublications() { try { const data = await publicationCall({ action: 'catalog' }); state.catalog = data; const organizations=data.organizations||[]; $('publication-organization').innerHTML=organizations.map((org)=>`<option value="${esc(org.id)}">${esc(org.name||org.id)}</option>`).join('') || (data.organization_id ? `<option value="${esc(data.organization_id)}">Organizația curentă</option>` : '<option value="">Nicio organizație</option>'); if (data.organization_id && !organizations.length) $('publication-organization').value=data.organization_id; renderPublicationSelectors(); } catch (error) { publicationStatus(error.message || 'Catalogul de publicare nu s-a putut încărca.', 'error'); } }
  async function publishPublication(action) { try { const fields = publicationFields(); if (!fields.module_key || !fields.guild_id || !/^\d{15,22}$/.test(fields.embed_channel_id)) throw Error('Alege modulul, serverul și un canal embed valid.'); if (fields.result_channel_id && !/^\d{15,22}$/.test(fields.result_channel_id)) throw Error('Canalul de rezultate trebuie să fie un ID Discord valid.'); publicationStatus(action === 'save_publication' ? 'Se salvează draftul…' : 'Se publică pe Discord…'); const data = await publicationCall({ action, ...fields }); publicationStatus(action === 'save_publication' ? 'Draft salvat.' : 'Modulul a fost publicat pe canalul embed.', 'ok'); if (data.publication) { $('publication-embed-channel').value = data.publication.embed_channel_id || ''; $('publication-result-channel').value = data.publication.result_channel_id || ''; } await loadPublications(); } catch (error) { publicationStatus(error.message || 'Publicarea a eșuat.', 'error'); } }
  $('add-module-button').onclick=()=>addButton(); $('add-module-field').onclick=()=>addField();
  $('module-handler').addEventListener('change', () => { const d=sample($('module-handler').value); if (!$('module-label').value.trim()) $('module-label').value=d.label || ''; if (!$('module-description').value.trim()) $('module-description').value=d.description || ''; if (!readButtons().length && !readFields().length) renderBuilders(d.buttons || [],d.form_schema || []); });
  $('module-new').addEventListener('click', () => { fill(null); $('module-key').value=`custom_modul_${Date.now().toString().slice(-5)}`; $('module-handler').value='none'; });
  $('module-preview').addEventListener('click', preview);
  $('module-save').addEventListener('click', async () => { try { const item=read(); if (!/^custom_[a-z0-9_]{2,70}$/.test(item.module_key)) throw Error('Folosește o cheie de forma custom_nume_modul.'); if (item.label.length<2) throw Error('Numele modulului este obligatoriu.'); if (!Array.isArray(item.definition.buttons) || !Array.isArray(item.definition.form_schema)) throw Error('JSON-ul pentru butoane sau câmpuri este invalid.'); await call({action:'save_module', ...item}); status('Șablonul modulului a fost salvat.', 'ok'); await load(); } catch (error) { status(error.message || 'Salvarea a eșuat.', 'error'); } });
  $('publication-save')?.addEventListener('click', () => publishPublication('save_publication'));
  $('publication-publish')?.addEventListener('click', () => publishPublication('publish'));
  $('publication-repair')?.addEventListener('click', () => { const current = (state.catalog.publications || []).find((p) => p.module_key === $('publication-module').value && p.target === $('publication-target').value); if (current?.message_id) $('publication-embed-channel').dataset.messageId = current.message_id; publishPublication('repair'); });
  if (!$('publication-sync') && $('publication-repair')?.parentElement) { const button=document.createElement('button'); button.id='publication-sync'; button.className='button'; button.type='button'; button.textContent='⚡ Sincronizează slash'; $('publication-repair').parentElement.appendChild(button); }
  $('publication-sync')?.addEventListener('click', async () => { try { const guildId=$('publication-guild').value; if (!guildId) throw Error('Alege mai întâi serverul Discord.'); publicationStatus('Se sincronizează comenzile slash…'); const data=await window.panelRequestJson('sync-discord-commands',{method:'POST',body:JSON.stringify({guild_id:guildId}),timeoutMs:30000}); publicationStatus(`${data.count || 0} comenzi slash sincronizate.`, 'ok'); } catch(error) { publicationStatus(error.message || 'Sincronizarea a eșuat.', 'error'); } });
  $('publication-refresh')?.addEventListener('click', loadPublications);
  const hydratePublication = () => { const current=currentPublication(); if (current) { $('publication-embed-channel').value=current.embed_channel_id || ''; $('publication-result-channel').value=current.result_channel_id || ''; $('publication-embed-channel').dataset.messageId=current.message_id || ''; } else { $('publication-embed-channel').value=''; $('publication-result-channel').value=''; $('publication-embed-channel').dataset.messageId=''; } renderPublicationPermissions(); };
  $('publication-module')?.addEventListener('change', hydratePublication); $('publication-target')?.addEventListener('change', hydratePublication); $('publication-guild')?.addEventListener('change', hydratePublication);
  $('publication-organization')?.addEventListener('change', () => { renderPublicationSelectors(); hydratePublication(); });
  async function load() { try { const data=await call({action:'list'}); state.modules=Array.isArray(data.modules)?data.modules:[]; renderList(); if (!state.selected && state.modules[0]) fill(state.modules[0]); status(`${state.modules.length} șabloane disponibile.`, 'ok'); await loadPublications(); } catch (error) { status(error.message || 'Nu s-au putut încărca șabloanele.', 'error'); } }
  if (typeof isPlatformAdmin === 'function' && !isPlatformAdmin()) { status('Acces permis doar administratorului global.', 'error'); return; }
  load();
})();
