(() => {
  const cfg = window.PANEL_SUPABASE_CONFIG || {};
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const labels = { pending: 'În așteptare', approved: 'Acceptată', rejected: 'Respinsă' };
  let access = { write: false, approve: false, platform_admin: false };
  let actorDiscordId = '';
  const notice = (message, error = false) => { const node = $('orders-notice'); node.textContent = message || ''; node.hidden = !message; node.style.borderColor = error ? '#991b1b' : '#7c2d12'; node.style.background = error ? '#450a0a' : '#431407'; node.style.color = error ? '#fecaca' : '#fed7aa'; };
  const api = async (action, body = {}) => { const token = localStorage.getItem('panel_session_token') || ''; const response = await fetch(`${cfg.url}/functions/v1/manage-orders`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: cfg.publishableKey || '', Authorization: `Bearer ${cfg.publishableKey || ''}`, 'x-panel-session': token }, body: JSON.stringify({ action, ...body }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); return data; };
  const render = (orders) => { const host = $('orders-list'); if (!orders.length) { host.innerHTML = '<div class="order-empty">Nu există încă comenzi.</div>'; return; } host.innerHTML = orders.map((order) => { const canDelete = access.platform_admin || access.approve || String(order.requested_by_discord_id) === String(actorDiscordId); return `<article class="order-row"><div class="order-head"><div><div class="order-title">${esc(order.item_name)}</div><div class="order-meta"><span class="order-pill">${esc(order.order_type)}</span><span class="order-pill">${esc(order.quantity)} buc.</span><span class="order-pill ${esc(order.status)}">${esc(labels[order.status] || order.status)}</span></div></div><time class="orders-muted">${esc(order.created_at ? new Date(order.created_at).toLocaleString('ro-RO') : '')}</time></div><div class="orders-muted" style="margin-top:8px">Solicitat de: ${esc(order.requested_by_name)}</div>${order.notes ? `<div class="order-note">${esc(order.notes)}</div>` : ''}${order.reviewed_by_name ? `<div class="orders-muted" style="margin-top:8px">Procesată de: ${esc(order.reviewed_by_name)} · ${esc(order.reviewed_at ? new Date(order.reviewed_at).toLocaleString('ro-RO') : '')}</div>` : ''}${access.approve && order.status === 'pending' ? `<div class="order-actions"><button class="orders-btn success" data-review="approved" data-id="${esc(order.id)}">Acceptă comanda</button><button class="orders-btn danger" data-review="rejected" data-id="${esc(order.id)}">Respinge</button></div>` : ''}${canDelete ? `<div class="order-actions"><button class="orders-btn danger" data-delete-order data-id="${esc(order.id)}">Șterge comanda</button></div>` : ''}</article>`; }).join(''); };
  const load = async () => { try { const data = await api('load'); access = data.access || access; actorDiscordId = String(data.actor_discord_id || ''); $('orders-actor').textContent = data.actor_name || 'Utilizatorul conectat'; $('orders-form').hidden = !access.write; $('order-type').innerHTML = (data.order_types || []).map((type) => `<option value="${esc(type)}">${esc(type)}</option>`).join(''); render(data.orders || []); } catch (error) { notice(error.message, true); $('orders-list').innerHTML = `<div class="order-empty">${esc(error.message)}</div>`; } };
  $('orders-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('create', { order_type: $('order-type').value, item_name: $('order-item').value, quantity: $('order-quantity').value, notes: $('order-notes').value }); event.target.reset(); $('order-quantity').value = '1'; notice('Comanda a fost trimisă și așteaptă aprobare.'); await load(); } catch (error) { notice(error.message, true); } });
  document.addEventListener('click', async (event) => { const deleteButton = event.target.closest('[data-delete-order]'); if (deleteButton) { if (!confirm('Ștergi această comandă? Acțiunea nu poate fi anulată.')) return; deleteButton.disabled = true; try { await api('delete', { id: deleteButton.dataset.id }); notice('Comanda a fost ștearsă.'); await load(); } catch (error) { notice(error.message, true); deleteButton.disabled = false; } return; } const button = event.target.closest('[data-review]'); if (!button) return; button.disabled = true; try { await api('review', { id: button.dataset.id, status: button.dataset.review }); notice(button.dataset.review === 'approved' ? 'Comanda a fost acceptată.' : 'Comanda a fost respinsă.'); await load(); } catch (error) { notice(error.message, true); button.disabled = false; } });
  load();
})();
