(() => {
  'use strict';
  const host=document.getElementById('custom-page'); const slug=new URLSearchParams(location.search).get('page') || '';
  const esc=(value)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const render=(page)=>{ const blocks=Array.isArray(page.content?.blocks)?page.content.blocks:[]; host.innerHTML=`<section class="custom-page-hero"><p class="eyebrow">Administrație Panel Pro</p><h1>${esc(page.icon||'📄')} ${esc(page.title)}</h1><p class="muted mt-2">${esc(page.description||'')}</p></section>${blocks.map((block)=>{if(block.type==='heading')return `<section class="custom-page-block"><h2>${esc(block.text)}</h2></section>`;if(block.type==='list')return `<section class="custom-page-block"><ul>${(block.items||[]).map((item)=>`<li>${esc(item)}</li>`).join('')}</ul></section>`;if(block.type==='link')return `<section class="custom-page-block"><a href="${esc(block.href)}">${esc(block.text)} →</a></section>`;return `<section class="custom-page-block ${block.type==='callout'?'border-cyan-400/40':''}"><p>${esc(block.text)}</p></section>`}).join('')}`; document.title=`${page.title} · Panel Pro`; };
  if(typeof isPlatformAdmin==='function'&&!isPlatformAdmin()){host.innerHTML='<section class="custom-page-hero"><h1>Acces restricționat</h1><p class="muted">Această pagină este disponibilă doar administratorului global.</p></section>';return;}
  if(!/^[a-z][a-z0-9-]{1,79}\.html$/.test(slug)){host.innerHTML='<section class="custom-page-hero"><h1>Pagina nu a fost găsită</h1></section>';return;}
  window.panelRequestJson('manage-platform-pages',{method:'POST',body:JSON.stringify({action:'list'}),timeoutMs:12000}).then((data)=>{const page=(data.pages||[]).find((item)=>item.slug===slug&&item.enabled!==false);if(!page)throw Error('Pagina nu există sau este dezactivată.');render(page);}).catch((error)=>{host.innerHTML=`<section class="custom-page-hero"><h1>Nu s-a putut încărca pagina</h1><p class="muted">${esc(error.message)}</p></section>`});
})();
