(() => {
  'use strict';
  const host = document.getElementById('custom-page');
  const slug = new URLSearchParams(location.search).get('page') || '';
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const safeHref = (value) => { const href=String(value||'').trim(); return href === '#' || /^[a-z][a-z0-9-]{1,79}\.html(?:[?#].*)?$/i.test(href) ? href : '#'; };
  const scheduleActive = (settings) => { const now=Date.now(); const publishAt=settings?.publish_at?Date.parse(settings.publish_at):NaN; const expiresAt=settings?.expires_at?Date.parse(settings.expires_at):NaN; return (!Number.isFinite(publishAt)||publishAt<=now)&&(!Number.isFinite(expiresAt)||expiresAt>now); };
  const render = (page) => {
    const settings=page.content?.settings||{}; const blocks=Array.isArray(page.content?.blocks)?page.content.blocks:[]; const layout=settings.layout==='wide'?'custom-page-wide':settings.layout==='two-column'?'custom-page-two-column':'';
    const renderBlock = (block) => {
      if(block.type==='hero')return `<section class="custom-page-block custom-page-hero-block"><h2>${esc(block.text)}</h2></section>`;
      if(block.type==='heading')return `<section class="custom-page-block"><h2>${esc(block.text)}</h2></section>`;
      if(block.type==='list')return `<section class="custom-page-block"><ul>${(block.items||[]).map((item)=>`<li>${esc(item)}</li>`).join('')}</ul></section>`;
      if(block.type==='cards')return `<section class="custom-page-block custom-page-cards">${(block.cards||[]).map((card)=>`<article><h2>${esc(card.title)}</h2><p>${esc(card.text)}</p>${card.href?`<a href="${esc(safeHref(card.href))}">Deschide →</a>`:''}</article>`).join('')}</section>`;
      if(block.type==='stats')return `<section class="custom-page-block custom-page-stats">${(block.items||[]).map((item)=>`<article><strong>${esc(item.value)}</strong><span>${esc(item.label)}</span><small>${esc(item.detail||'')}</small></article>`).join('')}</section>`;
      if(block.type==='faq')return `<section class="custom-page-block custom-page-faq">${(block.items||[]).map((item)=>`<details><summary>${esc(item.question)}</summary><p>${esc(item.answer)}</p></details>`).join('')}</section>`;
      if(block.type==='accordion')return `<section class="custom-page-block custom-page-faq">${(block.items||[]).map((item)=>`<details><summary>${esc(item.title)}</summary><p>${esc(item.text)}</p></details>`).join('')}</section>`;
      if(block.type==='banner')return `<aside class="custom-page-block custom-page-banner"><strong>${esc(block.tone||'info').toUpperCase()}</strong><p>${esc(block.text)}</p></aside>`;
      if(block.type==='form')return `<section class="custom-page-block"><form class="custom-page-form" data-page-form>${(block.fields||[]).map((field)=>{const label=esc(field.label),placeholder=`Completează ${esc(String(field.label||'').toLocaleLowerCase('ro-RO'))}`;return `<label>${label}${field.required?' *':''}${field.type==='textarea'?`<textarea name="${label}"${field.required?' required':''} placeholder="${placeholder}"></textarea>`:`<input type="${field.type==='number'?'number':field.type==='email'?'email':'text'}" name="${label}"${field.required?' required':''} placeholder="${placeholder}">`}</label>`;}).join('')}<button type="button" class="custom-page-button" data-form-demo>Trimite</button><p class="muted" data-form-status aria-live="polite"></p></form></section>`;
      if(block.type==='gallery')return `<section class="custom-page-block custom-page-gallery">${(block.items||[]).map((item)=>`<figure>${item.src?`<img src="${esc(item.src)}" alt="${esc(item.title||'Imagine')}" loading="lazy" decoding="async">`:'<div class="custom-page-gallery-placeholder" role="img" aria-label="Imagine indisponibilă">🖼️</div>'}<figcaption><strong>${esc(item.title)}</strong><br>${esc(item.text)}</figcaption></figure>`).join('')}</section>`;
      if(block.type==='timeline')return `<section class="custom-page-block"><ol class="custom-page-timeline">${(block.items||[]).map((item)=>`<li><strong>${esc(item.date)}</strong><p>${esc(item.text)}</p></li>`).join('')}</ol></section>`;
      if(block.type==='calculator')return `<section class="custom-page-block custom-page-calculator">${(block.fields||[]).map((field)=>`<label>${esc(field.label)}<input type="number" value="${esc(field.value)}" data-calculator-field></label>`).join('')}<output data-calculator-result>${esc(block.result||'Total: 0')}</output></section>`;
      if(block.type==='group')return `<section class="custom-page-block"><h2>${esc(block.title||'Grup')}</h2>${(block.blocks||[]).map(renderBlock).join('')}</section>`;
      if(block.type==='table')return `<section class="custom-page-block overflow-x-auto"><table><thead><tr>${(block.headers||[]).map((item)=>`<th>${esc(item)}</th>`).join('')}</tr></thead><tbody>${(block.rows||[]).map((row)=>`<tr>${row.map((cell)=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;
      if(block.type==='link'||block.type==='button')return `<section class="custom-page-block"><a class="custom-page-button" href="${esc(safeHref(block.href))}">${esc(block.text)} →</a></section>`;
      if(block.type==='divider')return '<hr class="custom-page-divider">';
      return `<section class="custom-page-block ${block.type==='callout'?'border-cyan-400/40':''}"><p>${esc(block.text)}</p></section>`;
    };
    host.innerHTML=`<section class="custom-page-hero ${layout}"><p class="eyebrow">Panel Pro · ${esc(settings.access||'global_admin')}</p><h1>${esc(page.icon||'📄')} ${esc(page.title)}</h1><p class="muted mt-2">${esc(page.description||'')}</p></section><div class="${layout}">${blocks.map(renderBlock).join('')}</div>`;
    host.querySelectorAll('[data-form-demo]').forEach((button)=>button.addEventListener('click',()=>{const form=button.closest('[data-page-form]');if(!form?.reportValidity())return;form.querySelector('[data-form-status]').textContent='Formularul este completat și pregătit pentru trimitere.';}));
    host.querySelectorAll('[data-calculator-field]').forEach((field)=>field.addEventListener('input',()=>{const values=[...host.querySelectorAll('[data-calculator-field]')].map((input)=>Number(input.value)||0);const total=values.reduce((sum,value)=>sum+value,0);host.querySelector('[data-calculator-result]').textContent=`Total: ${total}`;}));
    document.title=`${page.title} · Panel Pro`;
  };
  if(!/^[a-z][a-z0-9-]{1,79}\.html$/.test(slug)){host.innerHTML='<section class="custom-page-hero"><h1>Pagina nu a fost găsită</h1></section>';return;}
  const listAction=typeof isPlatformAdmin==='function'&&isPlatformAdmin()?'list':'public_list'; const device=window.matchMedia?.('(max-width: 767px)').matches?'mobile':'desktop'; window.panelRequestJson('manage-platform-pages',{method:'POST',body:JSON.stringify({action:listAction}),timeoutMs:12000,retry:true,retryPost:true,cache:'no-store',headers:{'x-panel-device':device}}).then((data)=>{const page=(data.pages||[]).find((item)=>item.slug===slug&&item.enabled!==false&&item.content?.settings?.publication!=='draft'&&scheduleActive(item.content?.settings||{}));if(!page)throw Error('Pagina nu există, nu este publicată sau este programată pentru mai târziu.');const access=page.content?.settings?.access||'global_admin';if(access==='global_admin'&&typeof isPlatformAdmin==='function'&&!isPlatformAdmin())throw Error('Această pagină este disponibilă doar administratorului global.');if(access==='authenticated'&&!localStorage.getItem('panel_session_token'))throw Error('Autentifică-te pentru a vedea această pagină.');render(page);}).catch((error)=>{host.innerHTML=`<section class="custom-page-hero"><h1>Nu s-a putut încărca pagina</h1><p class="muted">${esc(error.message)}</p></section>`});
})();
