(() => {
  const hideGlobalSearch = document.createElement('style'); hideGlobalSearch.textContent = 'body[data-task-page] .panel-header-tools,body[data-task-page] .panel-global-search-host,body[data-task-page] .panel-global-search{display:none!important}'; document.head.appendChild(hideGlobalSearch);
  const cfg = window.PANEL_SUPABASE_CONFIG || {};
  const type = document.body.dataset.taskType;
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const api = async (action, body = {}) => { const response = await fetch(`${cfg.url}/functions/v1/manage-platform-tasks`, { method:'POST', headers:{'Content-Type':'application/json',apikey:cfg.publishableKey||'',Authorization:`Bearer ${cfg.publishableKey||''}`,'x-panel-session':localStorage.getItem('panel_session_token')||''}, body:JSON.stringify({action, task_type:type, ...body}) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); return data; };
  const notice = (message, error = false) => { const node=$('task-notice'); node.textContent=message||''; node.hidden=!message; node.style.borderColor=error?'#991b1b':'#155e75'; node.style.background=error?'#450a0a':'#082f49'; node.style.color=error?'#fecaca':'#bae6fd'; };
  const statusLabel = { pending:'În așteptare', accepted:'Acceptat', refused:'Refuzat', cancelled:'Anulat', expired:'Expirat' };
  const formatDate = (value) => { const date=new Date(value); return Number.isFinite(date.getTime()) ? date.toLocaleString('ro-RO') : '—'; };
  const renderMembers = (members) => { $('task-members').innerHTML = members.length ? `<label class="task-member task-member-all"><input id="task-select-all" type="checkbox"><span>✅ Selectare totală<small>Selectează toți membrii afișați din serverul Discord</small></span></label>` + members.map((member) => `<label class="task-member"><input type="checkbox" value="${esc(member.discord_id)}"><span>${esc(member.name)}<small>${esc(member.panel_role || 'Membru')}</small></span></label>`).join('') : '<span class="task-muted">Nu există membri disponibili pe serverul Discord selectat.</span>'; $('task-members').querySelector('#task-select-all')?.addEventListener('change', (event) => { $('task-members').querySelectorAll('input[type="checkbox"][value]').forEach((input) => { input.checked = event.target.checked; }); }); };
  const renderTasks = (tasks) => { const host=$('task-list'); if (!tasks.length) { host.innerHTML='<div class="task-muted">Nu există task-uri trimise încă.</div>'; return; } host.innerHTML=tasks.map((task) => `<article class="task-row"><div class="task-title">${esc(task.description || task.title || 'Task')}</div><div class="task-meta"><span class="task-pill ${esc(task.status)}">${esc(statusLabel[task.status] || task.status)}</span><span class="task-pill">👤 ${esc(task.assignee_discord_id)}</span><span class="task-pill">📅 ${esc(formatDate(task.due_at))}</span></div>${task.response_note ? `<div class="task-description">${esc(task.response_note)}</div>` : ''}<div class="task-actions"><button class="task-btn" data-delete-task="${esc(task.id)}">Șterge</button></div></article>`).join(''); };
  const load = async () => { try { const data=await api('load'); renderMembers(data.members||[]); renderTasks(data.tasks||[]); if (data.access?.write === false) { $('task-form').hidden=true; notice('Ai acces de vizualizare, dar nu ai permisiunea de a trimite taskuri.'); } } catch(error) { notice(error.message,true); $('task-list').innerHTML=`<div class="task-muted">${esc(error.message)}</div>`; $('task-form').hidden=true; } };
  const setDefaultDue = () => { const date=new Date(Date.now()+7*86400000); date.setMinutes(date.getMinutes()-date.getTimezoneOffset()); $('task-due').value=date.toISOString().slice(0,16); };
  $('task-form').addEventListener('submit', async (event) => { event.preventDefault(); const button=event.currentTarget.querySelector('button[type="submit"]'); const assignees=[...document.querySelectorAll('#task-members input:checked')].map((input)=>input.value); if(!assignees.length) return notice('Selectează cel puțin un destinatar.',true); button.disabled=true; try { const data=await api('create',{assignees,description:$('task-description').value,due_at:new Date($('task-due').value).toISOString()}); $('task-description').value=''; notice(`Taskul a fost trimis prin DM către ${data.sent || 0} destinatar${Number(data.sent)===1?'':'i'}.${data.failures?.length?` Probleme: ${data.failures.join(' ')}`:''}`,Boolean(data.failures?.length)); await load(); } catch(error) { notice(error.message,true); } finally { button.disabled=false; } });
  document.addEventListener('click', async (event) => { const button=event.target.closest('[data-delete-task]'); if(!button||!confirm('Ștergi acest task?')) return; button.disabled=true; try { await api('delete',{id:button.dataset.deleteTask}); notice('Taskul a fost șters.'); await load(); } catch(error) { notice(error.message,true); button.disabled=false; } });
  setDefaultDue(); load();
})();
