import {createClient} from 'jsr:@supabase/supabase-js@2.112.3';
import {requirePanelSession} from '../_shared/panel-session.ts';
import {isPlatformAdminAccount} from '../_shared/platform-admin.ts';
import {getPlatformSecret} from '../_shared/platform-secrets.ts';
const headers={'Access-Control-Allow-Origin':'https://panel-pro.ro','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-panel-session','Content-Type':'application/json'};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const safeFetch=async(url:string,init:RequestInit={},timeout=8000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...init,signal:controller.signal})}finally{clearTimeout(timer)}};

Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response('ok',{headers});if(request.method!=='POST')return reply({error:'Metodă invalidă.'},405);
 try{
  const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}').default;if(!key)throw new Error('Cheia secretă Supabase lipsește.');
  const db=createClient(Deno.env.get('SUPABASE_URL')!,key),session=await requirePanelSession(db,request,0,true),body=await request.json(),organizationId=session.organization_id;if(!await isPlatformAdminAccount(db,session.discord_id))return reply({error:'Această funcție este rezervată administratorului platformei.'},403);
  const load=async()=>{const [{data:organization},{data:settings},{data:guilds},{data:roles},{data:platformSettings}]=await Promise.all([
   db.from('organizations').select('*').eq('id',organizationId).single(),db.from('organization_settings').select('*').eq('organization_id',organizationId).maybeSingle(),
   db.from('organization_guilds').select('*').eq('organization_id',organizationId).order('kind'),db.from('organization_role_mappings').select('*').eq('organization_id',organizationId).eq('enabled',true).order('permission_level'),db.from('app_settings').select('key,value').eq('organization_id',organizationId).in('key',['organization_access','contract_template'])]);
   return{organization,settings,guilds:guilds||[],roles:roles||[],platformSettings:Object.fromEntries((platformSettings||[]).map((item:any)=>[item.key,item.value]))};};
  if(body.action==='get'){
   const state=await load(),primary=state.guilds.find((g:any)=>g.kind==='primary'),secondary=state.guilds.find((g:any)=>g.kind==='secondary');
   const mappings=[...new Set(state.roles.map((role:any)=>Number(role.permission_level)).filter((level:number)=>level>=1&&level<=99))].sort((a,b)=>a-b).map(level=>{const p=state.roles.find((r:any)=>r.guild_id===primary?.guild_id&&Number(r.permission_level)===level),s=state.roles.find((r:any)=>r.guild_id===secondary?.guild_id&&Number(r.permission_level)===level);return{permission_level:level,discord_role_id:p?.discord_role_id||'',discord_role_name:p?.discord_role_name||'',discord_role_id_secondary:s?.discord_role_id||'',discord_role_name_secondary:s?.discord_role_name||'',panel_role:p?.panel_role||s?.panel_role||'',enabled:true};});
   return reply({config:{...(state.settings||{}),organization_name:state.organization.name,organization_code:state.organization.code,organization_description:state.organization.description,organization_logo:state.organization.logo_url,organization_banner:state.organization.banner_url,guild_id:primary?.guild_id||'',guild_id_secondary:secondary?.guild_id||''},mappings});
  }
  if(body.action==='discover_discord_roles'){
   const guildId=String(body.guild_id||'').trim(),bot=await getPlatformSecret(db,'discord_bot_token');if(!/^\d{15,22}$/.test(guildId))return reply({error:'Guild ID invalid.'},400);if(!bot)throw new Error('DISCORD_BOT_TOKEN lipsește.');
   const [gr,rr]=await Promise.all([fetch(`https://discord.com/api/v10/guilds/${guildId}`,{headers:{Authorization:`Bot ${bot}`}}),fetch(`https://discord.com/api/v10/guilds/${guildId}/roles`,{headers:{Authorization:`Bot ${bot}`}})]);if(!gr.ok||!rr.ok)return reply({error:`Botul nu poate accesa serverul (HTTP ${!gr.ok?gr.status:rr.status}).`},400);const guild=await gr.json(),roles=await rr.json();return reply({guild:{id:guild.id,name:guild.name},roles:(roles||[]).filter((r:any)=>!r.managed&&String(r.id)!==guildId).map((r:any)=>({id:String(r.id),name:String(r.name),position:Number(r.position)})).sort((a:any,b:any)=>b.position-a.position)});
  }
  if(body.action==='save'){
   const config=body.config||{},mappings=Array.isArray(body.mappings)?body.mappings:[];if(mappings.length!==7)throw new Error('Trebuie exact șapte niveluri.');
   const primaryId=String(config.guild_id||'').trim(),secondaryId=String(config.guild_id_secondary||'').trim();if(!/^\d{15,22}$/.test(primaryId))throw new Error('Guild ID principal invalid.');if(secondaryId&&!/^\d{15,22}$/.test(secondaryId))throw new Error('Guild ID secundar invalid.');
   await db.from('organizations').update({name:String(config.organization_name||'').trim(),code:config.organization_code||null,description:config.organization_description||null,logo_url:config.organization_logo||null,banner_url:config.organization_banner||null,updated_at:new Date().toISOString()}).eq('id',organizationId);
   const guildRows=[{organization_id:organizationId,guild_id:primaryId,kind:'primary',enabled:true},...(secondaryId?[{organization_id:organizationId,guild_id:secondaryId,kind:'secondary',enabled:true}]:[])];
   for(const row of guildRows){const {error}=await db.from('organization_guilds').upsert(row,{onConflict:'guild_id'});if(error)throw error;}
   const { data: existingSettings } = await db.from('organization_settings').select('discord_channel_routes').eq('organization_id', organizationId).maybeSingle();
   const {error:settingsError}=await db.from('organization_settings').upsert({
    organization_id:organizationId,
    discord_client_id:String(config.discord_client_id||'').trim(),
    panel_public_url:String(config.panel_public_url||'').replace(/\/$/,''),
    discord_channel_routes:config.discord_channel_routes ?? existingSettings?.discord_channel_routes ?? {},
    updated_by_discord_id:session.discord_id,
    updated_at:new Date().toISOString()
   },{onConflict:'organization_id'});if(settingsError)throw settingsError;
   await db.from('organization_role_mappings').delete().eq('organization_id',organizationId);
   const rows:any[]=[];for(const m of mappings){rows.push({organization_id:organizationId,guild_id:primaryId,discord_role_id:String(m.discord_role_id||''),discord_role_name:String(m.discord_role_name||''),panel_role:String(m.panel_role||''),permission_level:Number(m.permission_level),priority:Number(m.permission_level)*10,enabled:true});if(secondaryId&&m.discord_role_id_secondary)rows.push({organization_id:organizationId,guild_id:secondaryId,discord_role_id:String(m.discord_role_id_secondary),discord_role_name:String(m.discord_role_name_secondary||m.discord_role_name),panel_role:String(m.panel_role||''),permission_level:Number(m.permission_level),priority:Number(m.permission_level)*10,enabled:true});}
   if(rows.some(r=>!/^\d{15,22}$/.test(r.discord_role_id)||!r.discord_role_name||!r.panel_role||r.permission_level<1||r.permission_level>99))throw new Error('Una dintre mapările rolurilor este invalidă.');const {error:rolesError}=await db.from('organization_role_mappings').insert(rows);if(rolesError)throw rolesError;return reply({ok:true});
  }
  if(body.action==='diagnose'){
   const state=await load(),results:any[]=[],add=(id:string,category:string,label:string,status:string,message:string,started=Date.now())=>results.push({id,category,label,status,message,duration_ms:Date.now()-started});
   add('organization','Organizație','Numele organizației',state.organization?.name?.trim()?'ok':'error',state.organization?.name?.trim()?`„${state.organization.name}” este numele afișat membrilor autentificați.`:'Completează numele organizației.');
   add('organization-active','Organizație','Organizație activă',state.organization?.active?'ok':'error',state.organization?.active?'Organizația permite autentificarea membrilor.':'Organizația este dezactivată.');
   const primary=state.guilds.find((g:any)=>g.kind==='primary'&&g.enabled!==false),secondary=state.guilds.find((g:any)=>g.kind==='secondary'&&g.enabled!==false),bot=await getPlatformSecret(db,'discord_bot_token');
   add('bot-secret','Discord','Token bot Discord',bot?'ok':'error',bot?'Tokenul botului este configurat.':'DISCORD_BOT_TOKEN lipsește.');
   add('guild','Discord','Serverul principal',primary?'ok':'error',primary?`Guild configurat: ${primary.guild_name||primary.guild_id}.`:'Serverul principal lipsește sau este dezactivat.');
   add('guild-secondary','Discord','Serverul secundar',secondary?'ok':'warning',secondary?`Guild configurat: ${secondary.guild_name||secondary.guild_id}.`:'Nu există server secundar; se folosește serverul principal.');
   const botChannelDefinitions=[['organization','Anunțuri organizație'],['departments','Anunțuri birouri / angajați'],['pontaj','Pontaj și ture'],['weekly_reports','Rapoarte săptămânale'],['event_reminders','Evenimente și remindere'],['requests','Cereri / învoiri'],['requests_organization','Cereri organizație'],['requests_departments','Cereri birouri'],['contracts','Contracte'],['marketplace','Marketplace legal'],['illegal_marketplace','Marketplace ilegal'],['fines_organization','Amenzi organizație'],['fines_departments','Amenzi birouri'],['warnings_organization','Avertismente organizație'],['warnings_departments','Avertismente birouri'],['sanctions_organization','Sancțiuni organizație'],['sanctions_departments','Sancțiuni birouri'],['actions_organization','Acțiuni organizație'],['actions_organization_weekly','Clasament acțiuni'],['status_live','Status live'],['organization_expiration','Expirare organizație']];
   const routes=state.settings?.discord_channel_routes||{};
   for(const [channel,label] of botChannelDefinitions){
    for(const target of ['primary','secondary']){
     const started=Date.now(),entry=routes?.[channel]?.[target],channelId=String(entry?.channel_id||'').trim();
     if(!channelId){if(target==='primary'||secondary)add(`bot-channel-${channel}-${target}`,'Canale bot',`${label} · ${target==='primary'?'principal':'secundar'}`,secondary&&target==='secondary'?'warning':'warning',secondary&&target==='secondary'?'Canalul secundar nu este configurat.':'Canalul botului nu este configurat.',started);continue;}
     if(!bot){add(`bot-channel-${channel}-${target}`,'Canale bot',`${label} · ${target==='primary'?'principal':'secundar'}`,'error','Nu se poate verifica fără tokenul botului.',started);continue;}
     if(!/^\d{15,22}$/.test(channelId)){add(`bot-channel-${channel}-${target}`,'Canale bot',`${label} · ${target==='primary'?'principal':'secundar'}`,'error','Channel ID invalid.',started);continue;}
     try{const response=await safeFetch(`https://discord.com/api/v10/channels/${channelId}`,{headers:{Authorization:`Bot ${bot}`}});add(`bot-channel-${channel}-${target}`,'Canale bot',`${label} · ${target==='primary'?'principal':'secundar'}`,response.ok?'ok':'error',response.ok?'Botul poate accesa canalul Discord.':response.status===404?'Canalul nu există sau botul nu are acces.':`Discord a răspuns cu HTTP ${response.status}.`,started)}catch{add(`bot-channel-${channel}-${target}`,'Canale bot',`${label} · ${target==='primary'?'principal':'secundar'}`,'error','Canalul nu poate fi verificat.',started)}
    }
   }
   const summary=results.reduce((a:any,r:any)=>(a[r.status]++,a),{ok:0,warning:0,error:0});
   return reply({checked_at:new Date().toISOString(),results,summary});
  }
  if(body.action==='diagnose'){
   const state=await load(),results:any[]=[],add=(id:string,category:string,label:string,status:string,message:string,started=Date.now())=>results.push({id,category,label,status,message,duration_ms:Date.now()-started});
   add('organization','Organizație','Numele organizației',state.organization?.name?.trim()?'ok':'error',state.organization?.name?.trim()?`„${state.organization.name}” este numele afișat membrilor autentificați.`:'Completează numele organizației.');
   add('organization-active','Organizație','Organizație activă',state.organization?.active?'ok':'error',state.organization?.active?'Organizația permite autentificarea membrilor.':'Organizația este dezactivată.');
   const accessExpiry=String(state.platformSettings?.organization_access?.expires_at||''),accessExpiryMs=accessExpiry?Date.parse(accessExpiry):NaN,expiryConfigured=Boolean(accessExpiry),expiryValid=Number.isFinite(accessExpiryMs),remaining=expiryValid?accessExpiryMs-Date.now():null,organizationExpired=expiryValid&&accessExpiryMs<=Date.now();add('organization-expiry','Organizație','Termenul de activare',!expiryConfigured?'warning':!expiryValid?'error':organizationExpired?'error':'ok',!expiryConfigured?'Nu este configurat un termen de expirare.':!expiryValid?'Data expirării salvată este invalidă.':organizationExpired?`Organizația a expirat la ${new Date(accessExpiryMs).toLocaleString('ro-RO')}.`:`Activă până la ${new Date(accessExpiryMs).toLocaleString('ro-RO')}.`);const contract=state.platformSettings?.contract_template;add('contract-template','Contracte','Șablonul organizației',contract?.title&&contract?.template?'ok':'warning',contract?.title&&contract?.template?`Șablon activ: ${contract.title}.`:'Nu este configurat un contract propriu; se folosește șablonul standard.');
   const clientId=String(state.settings?.discord_client_id||''),panelUrl=String(state.settings?.panel_public_url||'');
   add('client-id','Configurare','Discord Client ID',/^\d{15,22}$/.test(clientId)?'ok':'error',/^\d{15,22}$/.test(clientId)?`Client ID configurat: ${clientId}.`:'Discord Client ID lipsește sau este invalid.');
   let validPanelUrl=false;try{const parsed=new URL(panelUrl);validPanelUrl=['http:','https:'].includes(parsed.protocol)}catch{}add('panel-url','Configurare','Adresa publică a panelului',validPanelUrl?'ok':'error',validPanelUrl?panelUrl:'URL-ul public al panelului lipsește sau este invalid.');
   const primary=state.guilds.find((g:any)=>g.kind==='primary'&&g.enabled!==false);add('guild','Discord','Serverul principal',primary?'ok':'error',primary?`Guild configurat: ${primary.guild_name||primary.guild_id}.`:'Serverul principal lipsește sau este dezactivat.');
   const bot=await getPlatformSecret(db,'discord_bot_token'),cron=await getPlatformSecret(db,'cron_secret');
   const owners=await getPlatformSecret(db,'platform_owner_discord_ids');add('bot-secret','Secrete','Token bot Discord',bot?'ok':'error',bot?'Tokenul botului este configurat.':'DISCORD_BOT_TOKEN lipsește.');add('owner-secret','Secrete','Administratorul platformei',owners?'ok':'error',owners?'Administratorul este configurat server-side.':'PLATFORM_OWNER_DISCORD_IDS lipsește.');add('cron-secret','Secrete','Protecția automatizării',cron?'ok':'error',cron?'CRON_SECRET este prezent.':'CRON_SECRET lipsește.');
   if(primary&&bot){const started=Date.now();if(organizationExpired){add('bot-guild-access','Discord','Accesul botului la server','warning','Organizația este expirată; verificarea serverului Discord nu se aplică până la reactivare.',started)}else{try{const [guildResponse,rolesResponse]=await Promise.all([safeFetch(`https://discord.com/api/v10/guilds/${primary.guild_id}`,{headers:{Authorization:`Bot ${bot}`}}),safeFetch(`https://discord.com/api/v10/guilds/${primary.guild_id}/roles`,{headers:{Authorization:`Bot ${bot}`}})]);const status=!guildResponse.ok?guildResponse.status:rolesResponse.status;add('bot-guild-access','Discord','Accesul botului la server',guildResponse.ok&&rolesResponse.ok?'ok':'error',guildResponse.ok&&rolesResponse.ok?'Botul vede serverul și lista de roluri.':status===404?'Discord nu găsește serverul sau botul nu mai este prezent. Verifică Guild ID-ul și invitația botului.':`Discord a răspuns cu HTTP ${status}.`,started)}catch{add('bot-guild-access','Discord','Accesul botului la server','error','Botul nu poate contacta serverul Discord sau cererea a expirat.',started)}}}
   const primaryRoles=state.roles.filter((r:any)=>r.guild_id===primary?.guild_id),levels=new Set(primaryRoles.map((r:any)=>Number(r.permission_level)));
   add('roles-count','Roluri Discord','Rolurile configurate',primaryRoles.length?'ok':'error',primaryRoles.length?`${primaryRoles.length} roluri Discord configurate pe ${levels.size} niveluri de acces.`:'Nu este configurat niciun rol Discord.');
   for(const [index,role] of primaryRoles.entries()){const valid=/^\d{15,22}$/.test(String(role.discord_role_id))&&String(role.panel_role||'').trim()&&Number(role.permission_level)>=1&&Number(role.permission_level)<=99;add(`role-${index+1}`,'Roluri Discord',role.discord_role_name||`Rolul ${index+1}`,valid?'ok':'error',valid?`Nivel ${role.permission_level} → ${role.panel_role}.`:'ID, nivel de acces sau nume în panel invalid.')}
   const webhookDefinitions=[['organization','Anunțuri organizație'],['departments','Anunțuri Birouri / Angajați'],['pontaj','Pontaj și ture'],['weekly_reports','Rapoarte săptămânale'],['event_reminders','Evenimente · remindere 14 zile'],['requests','Cereri / Învoiri general'],['requests_organization','Cereri / Învoiri organizație'],['requests_departments','Cereri / Învoiri birouri'],['contracts','Contracte'],['marketplace','Marketplace legal'],['illegal_marketplace','Marketplace ilegal'],['fines_organization','Amenzi organizație'],['fines_departments','Amenzi birouri'],['warnings_organization','Avertismente organizație'],['warnings_departments','Avertismente birouri'],['sanctions_organization','Sancțiuni financiare organizație'],['sanctions_departments','Sancțiuni financiare birouri'],['actions_organization','Acțiuni organizație'],['actions_organization_weekly','Export săptămânal clasament Acțiuni'],['status_live','Status live'],['organization_expiration','Expirare organizație']];
   const legacyWebhookFields:any={pontaj:'pontaj_webhook_url',requests:'requests_webhook_url',contracts:'contracts_webhook_url',marketplace:'marketplace_webhook_url',illegal_marketplace:'illegal_marketplace_webhook_url'};
   if(organizationExpired){for(const [channel,label] of webhookDefinitions)add(`webhook-${channel}`,'Webhook-uri',label,'warning','Organizația este expirată; webhook-ul nu este verificat până la reactivare.');}else{
   for(const [channel,label] of webhookDefinitions){const started=Date.now(),route=state.settings?.webhook_routes?.[channel]||{},legacy=String(state.settings?.[legacyWebhookFields[channel]]||''),targets=[route?.primary?.enabled!==false?route?.primary?.url:'',route?.secondary?.enabled!==false?route?.secondary?.url:'',legacy].map((value:any)=>String(value||'').trim()).filter((value:string,index:number,array:string[])=>value&&array.indexOf(value)===index);if(!targets.length){add(`webhook-${channel}`,'Webhook-uri',label,'warning','Webhook necompletat; notificările acestei secțiuni nu vor ajunge pe Discord.',started);continue;}if(targets.some((url:string)=>!/^https:\/\/(?:canary\.|ptb\.)?discord(?:app)?\.com\/api\/webhooks\/\d+\/[\w.-]+/i.test(url))){add(`webhook-${channel}`,'Webhook-uri',label,'error','Una dintre adrese nu are formatul unui webhook Discord.',started);continue;}try{const responses=await Promise.all(targets.map((url:string)=>safeFetch(url)));const failed=responses.find((response:Response)=>!response.ok);add(`webhook-${channel}`,'Webhook-uri',label,failed?'error':'ok',failed?(failed.status===404?'Webhook-ul Discord a fost șters sau nu mai există. Generează un webhook nou și salvează-l în configurarea organizației.':`Discord a răspuns cu HTTP ${failed.status}.`):`${targets.length} webhook${targets.length===1?'':'uri'} Discord valide și accesibile.`,started)}catch{add(`webhook-${channel}`,'Webhook-uri',label,'error','Timeout sau eroare de rețea.',started)}}
   }
   const tables=['organizations','organization_settings','organization_guilds','organization_role_mappings','organization_members','panel_sessions','shifts','absences','app_settings','marketplace','marketplace_ilegal','profiles','illegal_locations','community_posts','community_poll_options','community_poll_votes','community_reactions','disciplinary_warnings','disciplinary_sanctions','organization_actions','admin_audit_log','panel_notifications','panel_notification_reads','organization_expiration_notifications','organization_lifecycle_events','organization_vouchers','scheduled_report_runs','user_accounts','users','platform_administrators','platform_user_bans'];
   const organizationScopedTables=new Set(['organizations','organization_settings','organization_guilds','organization_role_mappings','organization_members','panel_sessions','shifts','absences','app_settings','marketplace','marketplace_ilegal','profiles','illegal_locations','community_posts','community_poll_options','community_poll_votes','community_reactions','disciplinary_warnings','disciplinary_sanctions','organization_actions','admin_audit_log','panel_notifications','panel_notification_reads','organization_expiration_notifications','organization_lifecycle_events','organization_vouchers','scheduled_report_runs']);
   for(const table of tables){const started=Date.now();let query=db.from(table).select('*',{head:true,count:'exact'});if(organizationScopedTables.has(table))query=query.eq(table==='organizations'?'id':'organization_id',organizationId);const {error}=await query;add(`table-${table}`,'Baza de date',table,error?'error':'ok',error?error.message:organizationScopedTables.has(table)?'Tabel accesibil și izolat pe organizația activă.':'Tabel global accesibil pentru administrarea platformei.',started)}
   const {data:automationHealth,error:automationError}=await db.rpc('get_panel_automation_health');
   if(automationError){
    add('automation-health','Automatizări','Configurarea cron și Vault','warning','Nu s-a putut verifica starea joburilor automate. Aplică migrarea pentru verificarea automatizărilor și rulează din nou.',Date.now());
   }else{
    const automationChecks=[
     ['cron-weekly','Job raport săptămânal','weekly_shift_report'],
     ['cron-status-live','Job status live','status_live'],
     ['cron-expiration','Job notificări expirare','organization_expiration'],
    ];
    for(const [id,label,key] of automationChecks){const configured=automationHealth?.jobs?.[key]===true;add(id,'Automatizări',label,configured?'ok':'error',configured?'Jobul automat este programat.':'Jobul automat lipsește din pg_cron.',Date.now());}
    const vaultReady=automationHealth?.vault?.project_url===true&&automationHealth?.vault?.publishable_key===true&&automationHealth?.vault?.cron_secret===true;
    add('vault-secrets','Automatizări','Secrete Vault pentru cron',vaultReady?'ok':'error',vaultReady?'project_url, publishable_key și cron_secret sunt configurate în Vault.':'Lipsește cel puțin un secret Vault folosit de joburile cron.',Date.now());
   }
   const functions=['sync-discord-role','manage-discord-config','manage-community-posts','manage-public-feedback','send-discord-notification','close-expired-shifts','send-weekly-shift-report','send-organization-expiry-notifications','manage-admin-center','manage-organizations','manage-owned-organization','redeem-organization-voucher','status-live-sync','create-voucher-organization','get-organization-status','finalize-organization','manage-draft-organization','discover-draft-roles','discover-discord-channels','save-draft-roles','touch-panel-session','mark-tutorial-read','link-discord-account','link-email-discord-guild','list-email-discord-guilds','manage-email-account','manage-discord-account','update-user-account-settings','username-login'];
   const baseUrl=String(Deno.env.get('SUPABASE_URL')||'');for(const name of functions){const started=Date.now();try{const response=await safeFetch(`${baseUrl}/functions/v1/${name}`,{method:'OPTIONS'});add(`function-${name}`,'Funcții server',name,response.ok?'ok':'error',response.ok?'Funcția este publicată și răspunde.':`HTTP ${response.status}.`,started)}catch{add(`function-${name}`,'Funcții server',name,'error','Funcția nu răspunde sau cererea a expirat.',started)}}
   if(validPanelUrl){for(const file of ['index.html','login.html','organizatii.html','diagnostic.html','js/supabase-config.js','js/panel-layout.js']){const started=Date.now();try{const response=await safeFetch(`${panelUrl.replace(/\/$/,'')}/${file}`);add(`file-${file}`,'Fișiere publice',file,response.ok?'ok':'error',response.ok?'Fișier publicat și accesibil.':`HTTP ${response.status}.`,started)}catch{add(`file-${file}`,'Fișiere publice',file,'error','Fișierul nu poate fi accesat.',started)}}}
   const summary=results.reduce((a:any,r:any)=>(a[r.status]++,a),{ok:0,warning:0,error:0});return reply({checked_at:new Date().toISOString(),results,summary});
  }
  return reply({error:'Acțiune necunoscută.'},400);
 }catch(error){console.error(error);return reply({error:error instanceof Error?error.message:'Eroare internă.'},400)}
});
