-- Registru central pentru embedurile Panel Pro si istoricul livrarilor Discord.
-- Nu modifica politicile modulelor existente; pastreaza datele tehnice server-side.

BEGIN;

CREATE TABLE IF NOT EXISTS public.discord_message_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  route_key text NOT NULL,
  message_key text NOT NULL DEFAULT 'control',
  target text NOT NULL CHECK (target IN ('primary', 'secondary')),
  channel_id text NOT NULL CHECK (channel_id ~ '^[0-9]{15,22}$'),
  guild_id text CHECK (guild_id IS NULL OR guild_id ~ '^[0-9]{15,22}$'),
  message_id text CHECK (message_id IS NULL OR message_id ~ '^[0-9]{15,22}$'),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'stale', 'missing', 'failed')),
  operation text NOT NULL DEFAULT 'sync' CHECK (operation IN ('create', 'edit', 'recreate', 'verify', 'sync')),
  last_http_status integer,
  last_error text,
  delivery_count integer NOT NULL DEFAULT 0,
  last_delivered_at timestamptz,
  last_checked_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, route_key, message_key, target, channel_id)
);

CREATE INDEX IF NOT EXISTS discord_message_registry_org_status_idx
  ON public.discord_message_registry (organization_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS discord_message_registry_route_idx
  ON public.discord_message_registry (organization_id, route_key, message_key);

CREATE TABLE IF NOT EXISTS public.discord_delivery_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  registry_id uuid REFERENCES public.discord_message_registry(id) ON DELETE SET NULL,
  route_key text NOT NULL,
  message_key text NOT NULL DEFAULT 'control',
  target text NOT NULL CHECK (target IN ('primary', 'secondary')),
  channel_id text CHECK (channel_id IS NULL OR channel_id ~ '^[0-9]{15,22}$'),
  message_id text CHECK (message_id IS NULL OR message_id ~ '^[0-9]{15,22}$'),
  operation text NOT NULL DEFAULT 'sync' CHECK (operation IN ('create', 'edit', 'recreate', 'verify', 'sync')),
  status text NOT NULL CHECK (status IN ('success', 'failure')),
  http_status integer,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS discord_delivery_attempts_org_created_idx
  ON public.discord_delivery_attempts (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS discord_delivery_attempts_failure_idx
  ON public.discord_delivery_attempts (organization_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.discord_delivery_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  route_key text NOT NULL,
  message_key text NOT NULL DEFAULT 'control',
  target text NOT NULL CHECK (target IN ('primary', 'secondary')),
  channel_id text NOT NULL CHECK (channel_id ~ '^[0-9]{15,22}$'),
  message_id text CHECK (message_id IS NULL OR message_id ~ '^[0-9]{15,22}$'),
  payload jsonb NOT NULL,
  headers jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'succeeded', 'failed')),
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  last_error text,
  locked_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.discord_embed_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  route_key text NOT NULL,
  message_key text NOT NULL,
  payload jsonb NOT NULL,
  changed_by_discord_id text,
  change_type text NOT NULL DEFAULT 'delivered' CHECK (change_type IN ('delivered', 'restored')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS discord_embed_versions_lookup_idx
  ON public.discord_embed_versions (organization_id, route_key, message_key, created_at DESC);

CREATE INDEX IF NOT EXISTS discord_delivery_queue_due_idx
  ON public.discord_delivery_queue (status, next_attempt_at);
CREATE INDEX IF NOT EXISTS discord_delivery_queue_org_idx
  ON public.discord_delivery_queue (organization_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS discord_delivery_queue_one_open_per_message_idx
  ON public.discord_delivery_queue (organization_id, route_key, message_key, target, channel_id)
  WHERE status IN ('pending', 'processing');

CREATE OR REPLACE FUNCTION public.increment_discord_registry_delivery_count(p_registry_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path TO public
AS $$
  UPDATE public.discord_message_registry
     SET delivery_count = delivery_count + 1,
         updated_at = now()
   WHERE id = p_registry_id;
$$;

ALTER FUNCTION public.increment_discord_registry_delivery_count(uuid) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.increment_discord_registry_delivery_count(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_discord_registry_delivery_count(uuid) TO service_role;

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'retry-discord-delivery') THEN
    PERFORM cron.unschedule('retry-discord-delivery');
  END IF;
END $$;

SELECT cron.schedule(
  'retry-discord-delivery',
  '*/2 * * * *',
  $$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/discord-delivery-retry',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'publishable_key'),
      'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_secret')
    ),
    body := jsonb_build_object('action', 'process')
  );
  $$
);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'check-discord-routes') THEN
    PERFORM cron.unschedule('check-discord-routes');
  END IF;
END $$;

SELECT cron.schedule(
  'check-discord-routes',
  '0 * * * *',
  $$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/discord-route-health',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'publishable_key'),
      'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_secret')
    ),
    body := jsonb_build_object('action', 'check')
  );
  $$
);

CREATE OR REPLACE FUNCTION public.get_panel_automation_health()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, cron, vault, pg_temp
AS $$
  SELECT jsonb_build_object(
    'jobs', jsonb_build_object(
      'weekly_shift_report', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-weekly-shift-report'),
      'weekly_contract_export', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-weekly-contract-export'),
      'weekly_action_report', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-weekly-action-report'),
      'organization_event_reminders', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-organization-event-reminders'),
      'close_expired_shifts', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-close-expired-shifts'),
      'wheel_timer', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'process-wheel-timers'),
      'status_live', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-status-live-sync'),
      'organization_expiration', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-organization-expiry-notifications'),
      'discord_delivery_retry', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'retry-discord-delivery'),
      'discord_route_health', EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'check-discord-routes')
    ),
    'vault', jsonb_build_object(
      'project_url', EXISTS (SELECT 1 FROM vault.decrypted_secrets WHERE name = 'project_url' AND NULLIF(decrypted_secret, '') IS NOT NULL),
      'publishable_key', EXISTS (SELECT 1 FROM vault.decrypted_secrets WHERE name = 'publishable_key' AND NULLIF(decrypted_secret, '') IS NOT NULL),
      'cron_secret', EXISTS (SELECT 1 FROM vault.decrypted_secrets WHERE name = 'cron_secret' AND NULLIF(decrypted_secret, '') IS NOT NULL)
    )
  );
$$;

ALTER FUNCTION public.get_panel_automation_health() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.get_panel_automation_health() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_panel_automation_health() TO service_role;

ALTER TABLE public.discord_message_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_delivery_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_delivery_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_embed_versions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.discord_message_registry FROM anon, authenticated;
REVOKE ALL ON TABLE public.discord_delivery_attempts FROM anon, authenticated;
REVOKE ALL ON TABLE public.discord_delivery_queue FROM anon, authenticated;
REVOKE ALL ON TABLE public.discord_embed_versions FROM anon, authenticated;
GRANT ALL ON TABLE public.discord_message_registry TO service_role;
GRANT ALL ON TABLE public.discord_delivery_attempts TO service_role;
GRANT ALL ON TABLE public.discord_delivery_queue TO service_role;
GRANT ALL ON TABLE public.discord_embed_versions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.discord_embed_versions_id_seq TO service_role;

COMMIT;
