-- Istoric și restaurare pentru conținutul creat de administratorul global.
create table if not exists public.platform_content_versions (
  id bigint generated by default as identity primary key,
  content_type text not null,
  content_key text not null,
  snapshot jsonb not null default '{}'::jsonb,
  changed_by_discord_id text,
  change_type text not null default 'saved',
  created_at timestamptz not null default now(),
  constraint platform_content_versions_type_check check (content_type in ('page', 'module'))
);

create index if not exists platform_content_versions_lookup_idx
  on public.platform_content_versions (content_type, content_key, created_at desc);

alter table public.platform_content_versions enable row level security;
revoke all on table public.platform_content_versions from anon, authenticated;

comment on table public.platform_content_versions is
  'Versiuni recuperabile pentru pagini și module Panel Pro create de administratorul global.';
