-- Runtime pentru modulele custom ale botului Panel Pro.
-- Modulele sunt globale; publicațiile și datele de utilizare sunt per organizație.

create table if not exists public.platform_module_publications (
  id uuid primary key default gen_random_uuid(),
  module_key text not null references public.platform_module_templates(module_key) on update cascade on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  guild_id text not null,
  target text not null default 'primary',
  embed_channel_id text not null,
  result_channel_id text,
  permissions jsonb not null default '{}'::jsonb,
  message_id text,
  status text not null default 'draft',
  last_error text,
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(module_key, organization_id, target),
  constraint panel_module_publication_target_check check (target in ('primary','secondary')),
  constraint panel_module_publication_status_check check (status in ('draft','published','error','disabled')),
  constraint panel_module_publication_guild_check check (guild_id ~ '^\d{15,22}$'),
  constraint panel_module_publication_embed_channel_check check (embed_channel_id ~ '^\d{15,22}$'),
  constraint panel_module_publication_result_channel_check check (result_channel_id is null or result_channel_id ~ '^\d{15,22}$'),
  constraint panel_module_publication_message_check check (message_id is null or message_id ~ '^\d{15,22}$')
);

alter table public.platform_module_publications
  add column if not exists permissions jsonb not null default '{}'::jsonb;

create index if not exists platform_module_publications_org_idx
  on public.platform_module_publications (organization_id, status, updated_at desc);

create table if not exists public.platform_module_submissions (
  id uuid primary key default gen_random_uuid(),
  module_key text not null references public.platform_module_templates(module_key) on update cascade on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  guild_id text not null,
  discord_id text not null,
  display_name text not null default '',
  values jsonb not null default '{}'::jsonb,
  status text not null default 'submitted',
  reviewed_by_discord_id text,
  reviewed_at timestamptz,
  result_message_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint panel_module_submission_status_check check (status in ('submitted','approved','rejected','closed')),
  constraint panel_module_submission_guild_check check (guild_id ~ '^\d{15,22}$')
);

create index if not exists platform_module_submissions_org_idx
  on public.platform_module_submissions (organization_id, module_key, created_at desc);

create table if not exists public.platform_module_events (
  id bigint generated by default as identity primary key,
  module_key text,
  organization_id uuid references public.organizations(id) on delete cascade,
  guild_id text,
  discord_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists platform_module_events_org_idx
  on public.platform_module_events (organization_id, created_at desc);

create table if not exists public.platform_module_rate_limits (
  module_key text not null,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  discord_id text not null,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (module_key, organization_id, discord_id),
  constraint panel_module_rate_limit_count_check check (request_count >= 0)
);

alter table public.platform_module_publications enable row level security;
alter table public.platform_module_submissions enable row level security;
alter table public.platform_module_events enable row level security;
alter table public.platform_module_rate_limits enable row level security;

revoke all on table public.platform_module_publications from anon, authenticated;
revoke all on table public.platform_module_submissions from anon, authenticated;
revoke all on table public.platform_module_events from anon, authenticated;
revoke all on table public.platform_module_rate_limits from anon, authenticated;

comment on table public.platform_module_publications is 'Publicații ale modulelor custom Panel Pro pe organizații și guild-uri Discord.';
comment on table public.platform_module_submissions is 'Cereri trimise prin modulele custom Panel Pro.';
comment on table public.platform_module_events is 'Audit și telemetrie pentru modulele custom Panel Pro.';
comment on table public.platform_module_rate_limits is 'Ferestre de cooldown pentru modulele custom Panel Pro.';
